### ISSUE TITLE
How are view statements calculated?

### ISSUE THREAD

**Issue by TomasaMuller** [karlb/litespread#3]
Hello, I see that you generate view statements for expressions like so

`SELECT * FROM (SELECT *, col7 / 2 AS "col8" FROM (SELECT rowid, "col1" AS "col1", "col2" AS "col2", "col3" AS "col3", "col4" AS "col4", "col5" AS "col5", "col6" AS "col6", col1 + col2 AS "col7" FROM table1)) ORDER BY col1 ASC`

Could you please highlight which part of the code generates these statements and how are these hierarchical statements calculated?

**Comment by karlb** [comment]
I didn't touch the code recently, so not sure if I get everything right. But I think it is as follows. The relevant part of the code is https://github.com/karlb/litespread/blob/master/src/backend/litespread.js#L34-L84.

Keep two lists of columns:
* availableCols has the columns for which all dependencies are resolved (initially all columns with plain data, so without any dependencies)
* todoCols has the columns which are not in the SQL query and might have unavailable dependencies (initially all columns)

The basic algorithm then is, for each column
1. Check is all column dependencies are in availableCols
2. If this is the case then move the column name from todoCols to availableCols
3. For each column moved this way, add it's formula to the SQL query, since it is ready to be evaluated (see the `s` variable using the squel query builder). Each iteration adds one outer layer to the query.

Does this answer your question?

**Comment by TomasaMuller** [comment]
Thank you for your time in answering this, and sorry for the delay. I have been busy this week, so couldn't get sufficient time to go through the code that you highlighted. Will hopefully have a look at it this weekend.
